### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rictinga**
Translated file:
https://github.com/GeoNode/documentation/blob/master/locale/en/LC_MESSAGES/index.po

### CODE REVIEW

**Review by afabiani — APPROVED** [review]

**Comment by afabiani** [comment]
@rictinga in order to take effect the files must go into the folder

`locale/pt/LC_MESSAGES`

by replacing the existing ones.

**Comment by JanetraEI** [comment]
> @rictinga in order to take effect the files must go into the folder
> 
> `locale/pt/LC_MESSAGES`
> 
> by replacing the existing ones.

Dear @afabiani, thank you for your intervention. We have lost upload permissions, we have all *.po files ready for upload, can you please grant us the necessary permissions so that we can finish the upload?
Thank you

**Comment by afabiani** [comment]
@JanetraEI could you please try again now?

**Comment by JanetraEI** [comment]
We still get "Uploads are disabled"

**Comment by afabiani** [comment]
Which github user are you using?

**Comment by JanetraEI** [comment]
JanetraEI

**Comment by afabiani** [comment]
@JanetraEI I guess you should have received in invitation or something

image

can you check your email?

**Comment by JanetraEI** [comment]
I have accepted your invitation, I have upload permissions now. Thank you

**Pull request merged**
