### PR TITLE
Windows installation: postgresql connection

### PR DESCRIPTION
**Pull request by iamtekson**
The documentation of the windows installation updated. The PostgreSQL database connection for the GeoNode added. I tested in my windows machine this code. This will be helpful for Windows users.

### CODE REVIEW

**Comment by t-book** [comment]
thanks, @iamtekson contributions to the docs can never be overrated! After merging your first commit I do wonder if it is good to mix the core linux instructions with windows or if it is better to dedicate a separate submenu to it. what do you think @afabiani  ?

**Comment by afabiani** [comment]
I prefer like it is now, a submenu for Windows setup. It looks to me more coherent with the "installation" section of the documentation.
But I'm not against having a dedicated section like "SPCGeoNode" too. I leave the decision to you @t-book .

About the docs, could not test locally yet, however they look quite useful.
I would probably suggest people to create a virtual environment on Windows in order to avoid installing the python requirements system wide.

**Comment by t-book** [comment]
thanks, @afabiani . I would merge for now and go through it again. In case it reads to complex I would move windows to a separate menu in a later step. @iamtekson I'm sharing Alessios suggestion, using a virtualenv is highly recommended. Can you kindly add this step?

**Comment by iamtekson** [comment]
Ya sure I will add

**Pull request merged**
