### PR TITLE
 Update Advanced Installation steps to work against Ubuntu 20.04LTS

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by gannebamm** [comment]
I can test this later today

**Comment by iamtekson** [comment]
I already installed geonode 2 times on ubuntu 20.04LTS. For me, [installation of geonode in 18.04](https://docs.geonode.org/en/master/install/advanced/core/#ubuntu-18-04) also works fine.

**Comment by t-book** [comment]
@afabiani Thanks. This is a great step forward! I've gone through the changes and haven't found anything. Unfortunately I won't find time to do a test install before Monday. It would be awesome if you  @gannebamm could do a test install?!

**Comment by afabiani** [comment]
@t-book @gannebamm I wrote those changes by following a new setup from scratch on a brand new WSL2 Ubuntu 20 instance on Windows 10

Nevertheless, it would be good that you could find some time to go through the steps and see if I missed something.

We don't want users getting angry with us anymore (hopefully)!

**Comment by t-book** [comment]
> We don't want users getting angry with us anymore (hopefully)!

Well true, but one should never forget that we all invest a lot of voluntary work ;)

**Comment by t-book** [comment]
This might be connected to not run too often in outdated links : https://github.com/GeoNode/documentation/issues/57

**Comment by afabiani** [comment]
@t-book I tried to mitigate that issue here

https://github.com/GeoNode/documentation/pull/64/files#diff-f997ec698d6807d12b7b6b0e377d2466461b84c54b764bb7ccef227d50c174b0R386

**Comment by gannebamm** [comment]
It works but throws some errors / warnings. Some may be related to my virtualization software (hyper-v). I installed it up to `paver setup/sync/start` and uploaded a ~20mb shapefile successfully. Here are my findings:

```shell
geonode@geonode-Virtual-Machine:~$ sudo add-apt-repository ppa:ubuntugis/ppa
E: The repository 'http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal Release' does not have a Release file.
```
I think we can safely ignore this.


```shell
geonode@geonode-Virtual-Machine:~$ sudo update-java-alternatives --jre-headless --jre --set java-1.8.0-openjdk-amd64
update-alternatives: error: no alternatives for policytool
update-alternatives: error: no alternatives for policytool
```
I encounter this all the time and up to now never had issues related to it. What do you guys say @afabiani @t-book 

on layer upload:
```shell
Handler dispatch failed; nested exception is java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
geonode.layers.models.Layer.DoesNotExist: Layer matching query does not exist.
```

as well as:
```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/geonode/geonode/layers/utils.py", line 1055, in create_thumbnail
    image = _prepare_thumbnail_body_from_opts(request_body)
  File "/opt/geonode/geonode/geoserver/helpers.py", line 2191, in _prepare_thumbnail_body_from_opts
    raise e
  File "/opt/geonode/geonode/geoserver/helpers.py", line 2187, in _prepare_thumbnail_body_from_opts
    image = _render_thumbnail(_img_request_template, width=width, height=height)
  File "/opt/geonode/geonode/geoserver/helpers.py", line 1995, in _render_thumbnail
    raise e
  File "/opt/geonode/geonode/geoserver/helpers.py", line 1976, in _render_thumbnail
    raise Exception(content)
Exception: Handler dispatch failed; nested exception is java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
Internal Server Error: /api/o/v4/tokeninfo/
Traceback (most recent call last):
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```
I think both are also not critical, since the upload worked and the thumbnail was created.

**Comment by gannebamm** [comment]
I now have to switch to some other tasks, but if I shall also test the rest of the setup, drop me a line here and I´ll come back to it later.

**Comment by afabiani** [comment]
@gannebamm those errors are normal when using SQLite. They will disappear with postgis.

There's a big warning for that on the docs.

**Comment by jkariukidev** [comment]
> It works but throws some errors / warnings. Some may be related to my virtualization software (hyper-v). I installed it up to `paver setup/sync/start` and uploaded a ~20mb shapefile successfully. Here are my findings:
> 
> ```shell
> geonode@geonode-Virtual-Machine:~$ sudo add-apt-repository ppa:ubuntugis/ppa
> E: The repository 'http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal Release' does not have a Release file.
> ```
> 
> I think we can safely ignore this.
> 
> ```shell
> geonode@geonode-Virtual-Machine:~$ sudo update-java-alternatives --jre-headless --jre --set java-1.8.0-openjdk-amd64
> update-alternatives: error: no alternatives for policytool
> update-alternatives: error: no alternatives for policytool
> ```
> 
> I encounter this all the time and up to now never had issues related to it. What do you guys say @afabiani @t-book
> 
> on layer upload:
> 
> ```shell
> Handler dispatch failed; nested exception is java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
> Traceback (most recent call last):
>   File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 538, in get_or_create
>     return self.get(**kwargs), False
>   File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
>     raise self.model.DoesNotExist(
> geonode.layers.models.Layer.DoesNotExist: Layer matching query does not exist.
> ```
> 
> as well as:
> 
> ```shell
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/geonode/geonode/layers/utils.py", line 1055, in create_thumbnail
>     image = _prepare_thumbnail_body_from_opts(request_body)
>   File "/opt/geonode/geonode/geoserver/helpers.py", line 2191, in _prepare_thumbnail_body_from_opts
>     raise e
>   File "/opt/geonode/geonode/geoserver/helpers.py", line 2187, in _prepare_thumbnail_body_from_opts
>     image = _render_thumbnail(_img_request_template, width=width, height=height)
>   File "/opt/geonode/geonode/geoserver/helpers.py", line 1995, in _render_thumbnail
>     raise e
>   File "/opt/geonode/geonode/geoserver/helpers.py", line 1976, in _render_thumbnail
>     raise Exception(content)
> Exception: Handler dispatch failed; nested exception is java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
> Internal Server Error: /api/o/v4/tokeninfo/
> Traceback (most recent call last):
>   File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/geonode/.virtualenvs/geonode/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
>     return Database.Cursor.execute(self, query, params)
> sqlite3.OperationalError: database is locked
> ```
> 
> I think both are also not critical, since the upload worked and the thumbnail was created.

Use `sudo update-alternatives --config java` command to show available java configs. The output is as below in Ubuntu 18.04.
```
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number:
```
In this case number 2 is the default (indicated by the asterisk). If not type the number and click enter on your keyboard. I hopt this information helps.

**Pull request merged**
